security:

    providers:

        our_db_provider:
            entity:
                class: App\Entity\Participant
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profile|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            user_checker: App\Security\UserChecker
            guard:
                authenticators:
                    - App\Security\ConnexionAuthenticator
            logout:
                path: app_logout
                target: app_login
            remember_me: # durée par défaut : 1 an
                secret: '%env(APP_SECRET)%'
                path: /

    encoders:
        App\Entity\Participant:
            algorithm: auto

    access_control:
        - { path: ^/sortie, roles: ROLE_USER }
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }